### PR TITLE
[ENHANCEMENT]: adding an ajax prefilter to an initializer

### PR DESCRIPTION
**Pull request by williamsbdev**
This will include set the CSRF token in a request header for every ajax
request.

### CODE REVIEW

**Comment by toranb** [comment]
Awesome! The only reason I didn't knock this out was that I wanted to tdd this part w/ an acceptance test. Do you know if fauxjax supports this header stuff in 0.5.0 yet?

**Comment by williamsbdev** [comment]
It appears that fauxjax does not currently support any header stuff. I was
wondering about an acceptance test but the addon is really stripped down of
everything and essentially just a really simple NPM module. Should we add
back all the stuff that ember init gives you?

**Comment by toranb** [comment]
good point - I was planning to add just enough to acceptance test a simple http POST but if fauxjax won't capture this we might be out of luck. I'll pull this in for the moment - then I'll ping Jarrod on teh fauxjax side of the house!

**Comment by williamsbdev** [comment]
I'm working on adding an acceptance test right now as this will allow me to
experiment and help flush out an implementation for fauxjax to test the
request headers. Hold off on merging.

**Comment by toranb** [comment]
Sounds like a plan - also note you will need another file in addition to the addon/initializers

In the app folder you actually need to reference the func you exported (look at my ember-cli-simple-store example)

https://github.com/toranb/ember-cli-simple-store/blob/master/app/initializers/ember-cli-simple-store.js

https://github.com/toranb/ember-cli-simple-store/tree/master/addon/initializers

**Comment by williamsbdev** [comment]
Ahh..thanks for point that out. I will get that fixed.

**Comment by williamsbdev** [comment]
I've been unable to successfully test this functionality. Have you had any luck?

**Comment by toranb** [comment]
Honestly I didn't have much luck using the xhr stub library I've got the most experience with. At this point lets pull this in

**Comment by toranb** [comment]
I did the npm publish /added you as a collaborator here and on npm

**Comment by williamsbdev** [comment]
Thanks!

On Saturday, February 21, 2015, Toran Billups notifications@github.com
wrote:

> I did the npm publish /added you as a collaborator here and on npm
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/toranb/ember-cli-thymeleaf-csrf/pull/1#issuecomment-75377628
> .

## 

Sent from Gmail Mobile

**Pull request merged**
